services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3\Min\:
        resource: '../Classes/*'

    T3\Min\EventListener\TinysourceEventListener:
        tags:
            -   name: event.listener
                identifier: 'ext-min-tinysource'
                event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent
